/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng ký tài khoản mới
         * @description Tạo tài khoản mới và trả về access token; refresh token được set qua httpOnly cookie.
         *
         *     - **email**: định dạng email hợp lệ, unique
         *     - **password**: tối thiểu 8 ký tự, phải có chữ và số
         *     - **display_name**: tên hiển thị, 1-100 ký tự
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập
         * @description Đăng nhập bằng email + password.
         *     Trả về access token (JWT); refresh token được set qua httpOnly cookie.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xoay refresh token */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất thiết bị hiện tại */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng xuất toàn bộ thiết bị */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Profile */
        get: operations["get_my_profile_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Profile */
        patch: operations["update_my_profile_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change My Password */
        patch: operations["change_my_password_api_v1_users_me_password_patch"];
        trace?: never;
    };
    "/api/v1/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Avatar */
        post: operations["upload_avatar_api_v1_users_me_avatar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Folders
         * @description Lấy danh sách tất cả folders của user hiện tại.
         *     Sắp xếp theo tên A-Z.
         */
        get: operations["list_folders_api_v1_folders_get"];
        put?: never;
        /**
         * Create Folder
         * @description Tạo folder mới.
         *     - 201: Tạo thành công
         *     - 409: Tên folder đã tồn tại (trùng per user)
         */
        post: operations["create_folder_api_v1_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Folder
         * @description Xem chi tiết 1 folder.
         *     - 404: Không tồn tại hoặc không thuộc user hiện tại
         */
        get: operations["get_folder_api_v1_folders__folder_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Folder
         * @description Xóa folder.
         *     Sets bên trong KHÔNG bị xóa — folder_id của chúng tự động về NULL.
         *     - 204: Xóa thành công
         *     - 404: Không tồn tại hoặc không thuộc user hiện tại
         */
        delete: operations["delete_folder_api_v1_folders__folder_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Folder
         * @description Cập nhật folder (partial update — chỉ gửi field cần đổi).
         *     - 404: Không tồn tại hoặc không thuộc user hiện tại
         *     - 409: Tên mới đã được dùng bởi folder khác
         */
        patch: operations["update_folder_api_v1_folders__folder_id__patch"];
        trace?: never;
    };
    "/api/v1/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sets */
        get: operations["list_sets_api_v1_sets_get"];
        put?: never;
        /** Create Set */
        post: operations["create_set_api_v1_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Set */
        get: operations["get_set_api_v1_sets__set_id__get"];
        put?: never;
        post?: never;
        /** Delete Set */
        delete: operations["delete_set_api_v1_sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Update Set */
        patch: operations["update_set_api_v1_sets__set_id__patch"];
        trace?: never;
    };
    "/api/v1/sets/{set_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Set */
        post: operations["clone_set_api_v1_sets__set_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets/{set_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_api_v1_sets__set_id__cards_get"];
        put?: never;
        /** Create Card */
        post: operations["create_card_api_v1_sets__set_id__cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets/{set_id}/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Card */
        get: operations["get_card_api_v1_sets__set_id__cards__card_id__get"];
        put?: never;
        post?: never;
        /** Delete Card */
        delete: operations["delete_card_api_v1_sets__set_id__cards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Card */
        patch: operations["update_card_api_v1_sets__set_id__cards__card_id__patch"];
        trace?: never;
    };
    "/api/v1/sets/{set_id}/cards/{card_id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder Card */
        patch: operations["reorder_card_api_v1_sets__set_id__cards__card_id__order_patch"];
        trace?: never;
    };
    "/api/v1/sets/{set_id}/cards/{card_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Card Image Endpoint */
        post: operations["upload_card_image_endpoint_api_v1_sets__set_id__cards__card_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submit_answer_api_v1_sessions__session_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session_api_v1_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats Overview */
        get: operations["get_stats_overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sessions History */
        get: operations["get_sessions_history_api_v1_stats_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sets/{set_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Set Stats */
        get: operations["get_set_stats_api_v1_sets__set_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Detail */
        get: operations["get_user_detail_api_v1_admin_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sets */
        get: operations["list_sets_api_v1_admin_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Set */
        delete: operations["delete_set_api_v1_admin_sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Update Set */
        patch: operations["update_set_api_v1_admin_sets__set_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/stats/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Stats */
        get: operations["get_user_stats_api_v1_admin_stats_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Learning Stats */
        get: operations["get_learning_stats_api_v1_admin_stats_learning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/stats/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content Stats */
        get: operations["get_content_stats_api_v1_admin_stats_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_admin_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Config */
        patch: operations["update_config_api_v1_admin_config_patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveUserMetrics */
        ActiveUserMetrics: {
            /** Dau */
            dau: number;
            /** Mau */
            mau: number;
        };
        /** AdminContentStatsResponse */
        AdminContentStatsResponse: {
            /** Top Sets By Sessions */
            top_sets_by_sessions: components["schemas"]["TopSetItem"][];
            /** Top Sets By Clones */
            top_sets_by_clones: components["schemas"]["TopSetItem"][];
            /** Popular Tags */
            popular_tags: components["schemas"]["TagPopularity"][];
        };
        /** AdminLearningStatsResponse */
        AdminLearningStatsResponse: {
            /** Sessions Chart */
            sessions_chart: components["schemas"]["ChartPoint"][];
            /** Mode Distribution */
            mode_distribution: components["schemas"]["ModeDistributionItem"][];
            /** Avg Known Rate */
            avg_known_rate: number;
            /** Avg Accuracy */
            avg_accuracy: number;
        };
        /** AdminSetListItem */
        AdminSetListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Owner Email */
            owner_email: string;
            /** Is Public */
            is_public: boolean;
            /** Card Count */
            card_count: number;
            /** Total Sessions */
            total_sessions: number;
            /** Total Clones */
            total_clones: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdminSetListResponse */
        AdminSetListResponse: {
            /** Items */
            items: components["schemas"]["AdminSetListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /** AdminSetUpdateRequest */
        AdminSetUpdateRequest: {
            /** Is Public */
            is_public: boolean;
        };
        /** AdminSetUpdateResponse */
        AdminSetUpdateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Is Public */
            is_public: boolean;
        };
        /** AdminUserDetailResponse */
        AdminUserDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Streak */
            streak: number;
            /** Last Studied */
            last_studied: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Total Sets */
            total_sets: number;
            /** Total Cards */
            total_cards: number;
            /** Total Sessions */
            total_sessions: number;
            /** Devices */
            devices: components["schemas"]["DeviceInfo"][];
            /** Recent Sessions */
            recent_sessions: components["schemas"]["RecentSessionItem"][];
        };
        /** AdminUserListItem */
        AdminUserListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Streak */
            streak: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Studied */
            last_studied: string | null;
            /** Total Sets */
            total_sets: number;
            /** Total Sessions */
            total_sessions: number;
        };
        /** AdminUserListResponse */
        AdminUserListResponse: {
            /** Items */
            items: components["schemas"]["AdminUserListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /** AdminUserStatsResponse */
        AdminUserStatsResponse: {
            /** Growth */
            growth: components["schemas"]["ChartPoint"][];
            /** Streak Distribution */
            streak_distribution: components["schemas"]["StreakBucket"][];
            /** Churn Rate */
            churn_rate: number;
        };
        /** AdminUserUpdateRequest */
        AdminUserUpdateRequest: {
            /** Is Active */
            is_active?: boolean | null;
            /** Role */
            role?: string | null;
            /** Force Reset Password */
            force_reset_password?: boolean | null;
        };
        /** AdminUserUpdateResponse */
        AdminUserUpdateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Temp Password */
            temp_password?: string | null;
        };
        /** AnswerResponse */
        AnswerResponse: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** Is Correct */
            is_correct: boolean;
            /** Quality */
            quality: number;
            sm2: components["schemas"]["SM2Result"];
        };
        /** AnswerSubmit */
        AnswerSubmit: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** Is Correct */
            is_correct: boolean;
            /**
             * Quality
             * @description Bắt buộc nếu mode=learn (1–5). Các mode khác bỏ trống.
             */
            quality?: number | null;
            /**
             * User Answer
             * @description Text user nhập vào — chỉ dùng cho mode=test.
             */
            user_answer?: string | null;
            /**
             * Time Spent
             * @description Thời gian trả lời tính bằng milliseconds.
             */
            time_spent: number;
        };
        /** AvatarUploadResponse */
        AvatarUploadResponse: {
            /** Avatar Url */
            avatar_url: string;
            /**
             * Message
             * @default Avatar updated successfully
             */
            message: string;
        };
        /** Body_upload_avatar_api_v1_users_me_avatar_post */
        Body_upload_avatar_api_v1_users_me_avatar_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_upload_card_image_endpoint_api_v1_sets__set_id__cards__card_id__image_post */
        Body_upload_card_image_endpoint_api_v1_sets__set_id__cards__card_id__image_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CardCreate */
        CardCreate: {
            /** Front */
            front: string;
            /** Back */
            back?: string | null;
            /** Image Url */
            image_url?: string | null;
        };
        /**
         * CardInSession
         * @description Thông tin card trả về khi tạo session.
         */
        CardInSession: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Front */
            front: string;
            /** Back */
            back: string;
            /** Image Url */
            image_url?: string | null;
            /** Order */
            order: number;
            /** Next Review */
            next_review?: string | null;
            /** @default not_started */
            status: components["schemas"]["CardStatus"];
        };
        /** CardListResponse */
        CardListResponse: {
            /** Items */
            items: components["schemas"]["CardResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** CardReorderRequest */
        CardReorderRequest: {
            /** Prev Order */
            prev_order?: number | null;
            /** Next Order */
            next_order?: number | null;
        };
        /** CardResponse */
        CardResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Study Set Id
             * Format: uuid
             */
            study_set_id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Front */
            front: string;
            /** Back */
            back: string | null;
            /** Image Url */
            image_url: string | null;
            /** Order */
            order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CardStatus
         * @enum {string}
         */
        CardStatus: "not_started" | "learning" | "known";
        /** CardUpdate */
        CardUpdate: {
            /** Front */
            front?: string | null;
            /** Back */
            back?: string | null;
            /** Image Url */
            image_url?: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** ChartPoint */
        ChartPoint: {
            /** Date */
            date: string;
            /** Count */
            count: number;
        };
        /** DashboardResponse */
        DashboardResponse: {
            users: components["schemas"]["UserMetrics"];
            sets: components["schemas"]["SetMetrics"];
            sessions: components["schemas"]["SessionMetrics"];
            active_users: components["schemas"]["ActiveUserMetrics"];
            /** User Growth */
            user_growth: components["schemas"]["ChartPoint"][];
            /** Session Chart */
            session_chart: components["schemas"]["ChartPoint"][];
        };
        /** DeviceInfo */
        DeviceInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Device */
            device: string | null;
            /** Ip */
            ip: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Revoked */
            is_revoked: boolean;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** FolderCreate */
        FolderCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** FolderResponse */
        FolderResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FolderUpdate */
        FolderUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Device */
            device?: string | null;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserPublic"];
            tokens: components["schemas"]["TokenData"];
        };
        /**
         * MessageData
         * @description Dùng cho các response chỉ trả về 1 message (logout, logout-all...).
         */
        MessageData: {
            /** Message */
            message: string;
        };
        /** ModeDistributionItem */
        ModeDistributionItem: {
            mode: components["schemas"]["StudyMode"];
            /** Sessions */
            sessions: number;
            /** Avg Accuracy */
            avg_accuracy: number;
        };
        /** ModeStats */
        ModeStats: {
            /** Mode */
            mode: string;
            /** Sessions */
            sessions: number;
            /** Avg Accuracy */
            avg_accuracy: number;
            /** Last Studied */
            last_studied: string | null;
        };
        /** ProgressSummary */
        ProgressSummary: {
            /** Known */
            known: number;
            /** Learning */
            learning: number;
            /** Not Started */
            not_started: number;
            /** Known Rate */
            known_rate: number;
        };
        /** RecentSessionItem */
        RecentSessionItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Set Title */
            set_title: string;
            mode: components["schemas"]["StudyMode"];
            /** Cards Studied */
            cards_studied: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Ended At */
            ended_at: string | null;
        };
        /** RefreshResponse */
        RefreshResponse: {
            tokens: components["schemas"]["TokenData"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            user: components["schemas"]["UserPublic"];
            tokens: components["schemas"]["TokenData"];
        };
        /**
         * SM2Result
         * @description Kết quả SM-2 sau khi tính toán.
         */
        SM2Result: {
            /** Ease Factor */
            ease_factor: number;
            /** Interval */
            interval: number;
            /** Repetitions */
            repetitions: number;
            /**
             * Next Review
             * Format: date-time
             */
            next_review: string;
            status: components["schemas"]["CardStatus"];
        };
        /** SessionCreate */
        SessionCreate: {
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            mode: components["schemas"]["StudyMode"];
        };
        /** SessionCreateResponse */
        SessionCreateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            mode: components["schemas"]["StudyMode"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Cards */
            cards: components["schemas"]["CardInSession"][];
        };
        /** SessionEndResponse */
        SessionEndResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            mode: components["schemas"]["StudyMode"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Cards Studied */
            cards_studied: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /**
             * Accuracy
             * @description Phần trăm đúng, 0.0–100.0
             */
            accuracy: number;
        };
        /** SessionHistoryItem */
        SessionHistoryItem: {
            /** Date */
            date: string;
            /** Sessions */
            sessions: number;
            /** Cards Studied */
            cards_studied: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Accuracy */
            accuracy: number;
            /** Study Time Seconds */
            study_time_seconds: number;
        };
        /** SessionHistoryResponse */
        SessionHistoryResponse: {
            /** Range */
            range: string;
            /** Group By */
            group_by: string;
            /** Data */
            data: components["schemas"]["SessionHistoryItem"][];
        };
        /** SessionListItem */
        SessionListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Set Id
             * Format: uuid
             */
            set_id: string;
            /** Set Title */
            set_title: string;
            mode: components["schemas"]["StudyMode"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /** Cards Studied */
            cards_studied: number;
            /** Correct */
            correct: number;
            /** Incorrect */
            incorrect: number;
            /** Accuracy */
            accuracy: number;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Items */
            items: components["schemas"]["SessionListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /** SessionMetrics */
        SessionMetrics: {
            /** Today */
            today: number;
            /** Last 7D */
            last_7d: number;
            /** Last 30D */
            last_30d: number;
        };
        /** SetMetrics */
        SetMetrics: {
            /** Total */
            total: number;
            /** Public */
            public: number;
            /** Private */
            private: number;
        };
        /** SetStatsResponse */
        SetStatsResponse: {
            /** Set Id */
            set_id: string;
            /** Set Title */
            set_title: string;
            /** Card Count */
            card_count: number;
            progress_summary: components["schemas"]["ProgressSummary"];
            /** By Mode */
            by_mode: components["schemas"]["ModeStats"][];
            /** Total Sessions */
            total_sessions: number;
            /** Total Study Time Seconds */
            total_study_time_seconds: number;
        };
        /** StatsOverviewResponse */
        StatsOverviewResponse: {
            /** Streak */
            streak: number;
            /** Last Studied */
            last_studied: string | null;
            /** Total Cards Known */
            total_cards_known: number;
            /** Total Cards Learning */
            total_cards_learning: number;
            /** Total Sessions */
            total_sessions: number;
            /** Total Study Time Seconds */
            total_study_time_seconds: number;
            /** Sets Studied */
            sets_studied: number;
        };
        /** StreakBucket */
        StreakBucket: {
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /**
         * StudyMode
         * @enum {string}
         */
        StudyMode: "flashcard" | "learn" | "test" | "match";
        /** StudySetCreate */
        StudySetCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
        };
        /** StudySetResponse */
        StudySetResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /** Tags */
            tags: string[];
            /** Is Public */
            is_public: boolean;
            /** Card Count */
            card_count: number;
            /** Cloned From */
            cloned_from?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StudySetUpdate */
        StudySetUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Is Public */
            is_public?: boolean | null;
        };
        /** SuccessEnvelope[LoginResponse] */
        SuccessEnvelope_LoginResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["LoginResponse"];
        };
        /** SuccessEnvelope[MessageData] */
        SuccessEnvelope_MessageData_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["MessageData"];
        };
        /** SuccessEnvelope[RefreshResponse] */
        SuccessEnvelope_RefreshResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["RefreshResponse"];
        };
        /** SuccessEnvelope[RegisterResponse] */
        SuccessEnvelope_RegisterResponse_: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            data: components["schemas"]["RegisterResponse"];
        };
        /** SystemConfigResponse */
        SystemConfigResponse: {
            /** Initial Ease Factor */
            initial_ease_factor: number;
            /** Min Ease Factor */
            min_ease_factor: number;
            /** Known Threshold Days */
            known_threshold_days: number;
            /** Max Sets Per User */
            max_sets_per_user: number;
            /** Max Cards Per Set */
            max_cards_per_set: number;
            /** Max Image Size Mb */
            max_image_size_mb: number;
            /** Allow Registration */
            allow_registration: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SystemConfigUpdateRequest */
        SystemConfigUpdateRequest: {
            /** Initial Ease Factor */
            initial_ease_factor?: number | null;
            /** Min Ease Factor */
            min_ease_factor?: number | null;
            /** Known Threshold Days */
            known_threshold_days?: number | null;
            /** Max Sets Per User */
            max_sets_per_user?: number | null;
            /** Max Cards Per Set */
            max_cards_per_set?: number | null;
            /** Max Image Size Mb */
            max_image_size_mb?: number | null;
            /** Allow Registration */
            allow_registration?: boolean | null;
        };
        /** TagPopularity */
        TagPopularity: {
            /** Tag */
            tag: string;
            /** Count */
            count: number;
        };
        /** TokenData */
        TokenData: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** TopSetItem */
        TopSetItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Owner Email */
            owner_email: string;
            /** Value */
            value: number;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** UserMetrics */
        UserMetrics: {
            /** Total */
            total: number;
            /** Active */
            active: number;
            /** Inactive */
            inactive: number;
            /** New Today */
            new_today: number;
            /** New 7D */
            new_7d: number;
        };
        /** UserProfile */
        UserProfile: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Role */
            role: string;
            /** Streak */
            streak: number;
            /** Last Studied */
            last_studied?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserPublic
         * @description Thông tin user trả về trong response — không có password.
         */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Streak */
            streak: number;
            /** Last Studied */
            last_studied: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_RegisterResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_RefreshResponse_"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_MessageData_"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessEnvelope_MessageData_"];
                };
            };
        };
    };
    get_my_profile_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    update_my_profile_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_my_password_api_v1_users_me_password_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_avatar_api_v1_users_me_avatar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_avatar_api_v1_users_me_avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_folders_api_v1_folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"][];
                };
            };
        };
    };
    create_folder_api_v1_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_folder_api_v1_folders__folder_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_v1_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_folder_api_v1_folders__folder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sets_api_v1_sets_get: {
        parameters: {
            query?: {
                search?: string | null;
                folder_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_set_api_v1_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudySetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_set_api_v1_sets__set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_api_v1_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_set_api_v1_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudySetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_set_api_v1_sets__set_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudySetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_api_v1_sets__set_id__cards_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_card_api_v1_sets__set_id__cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_api_v1_sets__set_id__cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_api_v1_sets__set_id__cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_api_v1_sets__set_id__cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_card_api_v1_sets__set_id__cards__card_id__order_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_card_image_endpoint_api_v1_sets__set_id__cards__card_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_card_image_endpoint_api_v1_sets__set_id__cards__card_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                set_id?: string | null;
                mode?: components["schemas"]["StudyMode"] | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_api_v1_sessions__session_id__answers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_v1_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEndResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_overview_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverviewResponse"];
                };
            };
        };
    };
    get_sessions_history_api_v1_stats_sessions_get: {
        parameters: {
            query?: {
                range?: "7d" | "30d" | "90d";
                group_by?: "day" | "week";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_set_stats_api_v1_sets__set_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_admin_dashboard_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                search?: string | null;
                role?: string | null;
                is_active?: boolean | null;
                sort_by?: string;
                sort_order?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_detail_api_v1_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sets_api_v1_admin_sets_get: {
        parameters: {
            query?: {
                owner_id?: string | null;
                is_public?: boolean | null;
                sort_by?: string;
                sort_order?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_api_v1_admin_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_set_api_v1_admin_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSetUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSetUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_stats_api_v1_admin_stats_users_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_learning_stats_api_v1_admin_stats_learning_get: {
        parameters: {
            query?: {
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLearningStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_stats_api_v1_admin_stats_content_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminContentStatsResponse"];
                };
            };
        };
    };
    get_config_api_v1_admin_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfigResponse"];
                };
            };
        };
    };
    update_config_api_v1_admin_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
